# Random Forest Exercise
Predecir la temperatura de mañana

### 1. Librerías

In [1]:
#Importacion de la Libreria pandas
import pandas as pd
#Importacion de la libreria numpy
import numpy as np

### 2. Leer fichero

In [19]:
temp = pd.read_csv("../01. Flat Files/temps.csv")
temp.head()

,year,month,day,week,temp_2,temp_1,average,actual,forecast_noaa,forecast_acc,forecast_under,friend
0,2016,1,1,Fri,45,45,45.6,45,43,50,44,29
1,2016,1,2,Sat,44,45,45.7,44,41,50,44,61
2,2016,1,3,Sun,45,44,45.8,41,43,46,47,56
3,2016,1,4,Mon,44,41,45.9,40,44,48,46,53
4,2016,1,5,Tues,41,40,46.0,44,46,46,46,41

### 3. Transformar campo nominal a numérico
One Hot encoding

In [20]:
#dictWeek = {"Fri":5,"Mon":1,"Sat":6,"Sun":7,"Thurs":4,"Tues":2,"Wed":3}
#temp["week"] = temp["week"].replace(dictWeek)
#temp.head()

dfDummiesWeek = pd.get_dummies(temp["week"])

temp = pd.concat([temp,dfDummiesWeek],axis=1)
temp.head()

temp = temp.drop(columns={"week"})
temp.head()

,year,month,day,temp_2,temp_1,average,actual,forecast_noaa,forecast_acc,forecast_under,friend,Fri,Mon,Sat,Sun,Thurs,Tues,Wed
0,2016,1,1,45,45,45.6,45,43,50,44,29,1,0,0,0,0,0,0
1,2016,1,2,44,45,45.7,44,41,50,44,61,0,0,1,0,0,0,0
2,2016,1,3,45,44,45.8,41,43,46,47,56,0,0,0,1,0,0,0
3,2016,1,4,44,41,45.9,40,44,48,46,53,0,1,0,0,0,0,0
4,2016,1,5,41,40,46.0,44,46,46,46,41,0,0,0,0,0,1,0

### 4. Identificación de "label"

In [21]:
x = temp.drop(columns={"actual"})
y = temp["actual"]

### 5. Datos de Training and Testing

In [23]:
from sklearn.model_selection import train_test_split

xTrain, xTest, yTrain, yTest = train_test_split(x,y,test_size=0.3,random_state=101)

### 6. Tomamos una referencia de error con la media histórica

In [25]:
yPredict1 = x["average"]
errores = abs(y-yPredict1)
print("Error con la media historica: ",errores.mean())
del errores,yPredict1

Error con la media historica:  4.933045977011492

### 7. Entrenamos el Forest

Podemos probar con otros parámetros!

In [47]:
from sklearn.ensemble import RandomForestRegressor

rfr = RandomForestRegressor()

rfr.fit(xTrain,yTrain)

RandomForestRegressor(bootstrap=True, ccp_alpha=0.0, criterion='mse',
                      max_depth=None, max_features='auto', max_leaf_nodes=None,
                      max_samples=None, min_impurity_decrease=0.0,
                      min_impurity_split=None, min_samples_leaf=1,
                      min_samples_split=2, min_weight_fraction_leaf=0.0,
                      n_estimators=100, n_jobs=None, oob_score=False,
                      random_state=None, verbose=0, warm_start=False)

### 8. Predicciones sobre los datos Test

In [51]:
yPredict = rfr.predict(xTest)

,year,month,day,temp_2,temp_1,average,forecast_noaa,forecast_acc,forecast_under,friend,Fri,Mon,Sat,Sun,Thurs,Tues,Wed
0,2016,1,1,45,45,45.6,43,50,44,29,1,0,0,0,0,0,0
1,2016,1,2,44,45,45.7,41,50,44,61,0,0,1,0,0,0,0
2,2016,1,3,45,44,45.8,43,46,47,56,0,0,0,1,0,0,0
3,2016,1,4,44,41,45.9,44,48,46,53,0,1,0,0,0,0,0
4,2016,1,5,41,40,46.0,46,46,46,41,0,0,0,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
343,2016,12,27,42,42,45.2,41,50,47,47,0,0,0,0,0,1,0
344,2016,12,28,42,47,45.3,41,49,44,58,0,0,0,0,0,0,1
345,2016,12,29,47,48,45.3,43,50,45,65,0,0,0,0,1,0,0
346,2016,12,30,48,48,45.4,44,46,44,42,1,0,0,0,0,0,0
347,2016,12,31,48,57,45.5,42,48,47,57,0,0,1,0,0,0,0

### 9. Visualización del árbol

In [58]:
from sklearn.tree import export_graphviz

arbol = rfr.estimators_[5] 

export_graphviz(arbol,out_file='tree_nonlimited.dot',feature_names = list(x.columns),rounded = True, 
                proportion = False,precision = 2,filled = True)

import pydot 

pydot.graph_from_dot_file('tree_nonlimited.dot').write_png('tree_nonlimited.png')

# Display in jupyter notebook
from IPython.display import Image
Image(filename = 'tree_nonlimited.png')

FileNotFoundError: [WinError 2] The system cannot find the file specified

### 10. Importancia de las variables

### 11. Nuevo modelo con los dos inputs más importantes

### 12. Visualizaciones